export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Main } from "./Main";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as Timeline } from "./Experience";
export { default as Project } from "./Project";
export { default as Blog } from "./Blog";
export { default as Contact } from "./Contact";
